name: Pull request to unstable

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - unstable

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      REPOSITORY_OWNER: StanleyProjects
      REPOSITORY_NAME: KotlinExtension.OkHttp
      VCS_PAT: ${{secrets.PERSONAL_ACCESS_TOKEN}}
      TELEGRAM_BOT_ID: ${{secrets.TELEGRAM_BOT_ID}}
      TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
      TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID_COMMON}}
    steps:
      - run: |
          echo "HOME=$(echo ~)" >> $GITHUB_ENV
          echo "BUILD_PATH=$HOME/$(jq -r .workflow $GITHUB_EVENT_PATH | base64)/$GITHUB_RUN_NUMBER/$GITHUB_RUN_ID" \
           >> $GITHUB_ENV
      - run: |
          mkdir -p $BUILD_PATH/repository
          git -C $BUILD_PATH/repository init
          git -C $BUILD_PATH/repository remote add origin \
           https://$VCS_PAT@github.com/$REPOSITORY_OWNER/$REPOSITORY_NAME.git
          git -C $BUILD_PATH/repository fetch --depth=1 origin $(jq -r .pull_request.head.sha $GITHUB_EVENT_PATH)
          git -C $BUILD_PATH/repository checkout FETCH_HEAD
      - run: |
          docker build --no-cache \
           --build-arg REPOSITORY_OWNER=$REPOSITORY_OWNER \
           --build-arg REPOSITORY_NAME=$REPOSITORY_NAME \
           --build-arg VCS_PAT=$VCS_PAT \
           -t image.verify:$GITHUB_RUN_NUMBER \
           -f $BUILD_PATH/repository/buildSrc/src/main/resources/docker/pr/unstable.docker $BUILD_PATH/repository
          echo "REPOSITORY_OWNER=$REPOSITORY_OWNER" > /tmp/build${GITHUB_RUN_NUMBER}.env
          echo "REPOSITORY_NAME=$REPOSITORY_NAME" >> /tmp/build${GITHUB_RUN_NUMBER}.env
          echo "GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER" >> /tmp/build${GITHUB_RUN_NUMBER}.env
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID" >> /tmp/build${GITHUB_RUN_NUMBER}.env
          echo "TELEGRAM_BOT_ID=$TELEGRAM_BOT_ID" >> /tmp/build${GITHUB_RUN_NUMBER}.env
          echo "TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID" >> /tmp/build${GITHUB_RUN_NUMBER}.env
          docker run --rm \
           -e VCS_PAT=$VCS_PAT \
           -e TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN \
           --env-file /tmp/build${GITHUB_RUN_NUMBER}.env \
           --name container.verify image.verify:$GITHUB_RUN_NUMBER
